### PR TITLE
Attempt to publish /html/ and /lang/ in a separate repo

### PR DESCRIPTION
**Pull request by teolemon**
Attempt to publish /html/ and /lang/ in a separate repo based on @hangy 's feedback

### CODE REVIEW

**Review by hangy — COMMENTED** [review]
I don't have time to review everything right now, but CSS, JS, and most images included from the server should definitely be part of the server repository.

**Comment by teolemon** [comment]
The underlying fact: the file structure is a mess.

**Comment by stephanegigandet** [comment]
Moving some things to a separate repo is a very good idea, but a PR with 10k files changed is impossible to review.

I would suggest to create a bug and/or a wiki page that describes the changes planned.

And the key to success for something like that is baby steps: moving things one by one.

e.g. a good way to start could be to:

1. mv the /lang dir from openfoodfacts-server to openfoodfacts-resources (or maybe to make things even cleaner, to a new repo openfoodfacts-web, it's unclear if everything in openfoodfacts-resources is supposed to be available as-is on the web server).

2. create a /html/images/texts/ directory in openfoodfacts-web so that we can put the new images needed by texts there (we don't have to move the existing ones right away).

That way for deployment, we can just copy /lang and /html to /srv/off/ and it will work.

And that's it, that would be already be enough of a big change for a first step. Then we can have a look at what we have in /html/ to see what we should move, one by one.

**Review by stephanegigandet — CHANGES_REQUESTED** [review]
Moving some things to a separate repo is a very good idea, but a PR with 10k files changed is impossible to review.

I would suggest to create a bug and/or a wiki page that describes the changes planned.

And the key to success for something like that is baby steps: moving things one by one.

e.g. a good way to start could be to:

mv the /lang dir from openfoodfacts-server to openfoodfacts-resources (or maybe to make things even cleaner, to a new repo openfoodfacts-web, it's unclear if everything in openfoodfacts-resources is supposed to be available as-is on the web server).

create a /html/images/texts/ directory in openfoodfacts-web so that we can put the new images needed by texts there (we don't have to move the existing ones right away).

That way for deployment, we can just copy /lang and /html to /srv/off/ and it will work.

And that's it, that would be already be enough of a big change for a first step. Then we can have a look at what we have in /html/ to see what we should move, one by one.

**Comment by teolemon** [comment]
Essentially, I

**Pull request closed without merging**
