### PR TITLE
Add SVG / PNG logo images for zh-tw

### PR DESCRIPTION
**Pull request by Cypresslin**
Add translated SVG / PNG logo for zh-tw locale.

### CODE REVIEW

**Comment by teolemon** [comment]
@stephanegigandet needs to be deployed, along with many other new logos

**Comment by teolemon** [comment]
@Cypresslin @hangy 
It needs to be merged again the server repo

**Comment by Cypresslin** [comment]
@teolemon 
Hi, do you mean that I will need to make changes in openfoodfacts-server/html/images/misc/ and create another merge request in that repo?

**Comment by teolemon** [comment]
yes, so that it can be deployed into prod when merged.

**Comment by Cypresslin** [comment]
https://github.com/openfoodfacts/openfoodfacts-server/pull/871

**Pull request merged**
